fennel-ai/client

docs/examples/api-reference/source.py
docs/pages/api-reference/sources.md

documentation: Add documentation for hudi

---

docs/pages/api-reference/expectations.md

documentation: Improve the documentation for expectation api reference

---

docs/examples/api-reference/operators_ref.py
docs/examples/datasets/operators.py
docs/examples/datasets/pipelines.py
docs/examples/getting-started/quickstart.py
docs/examples/overview/concepts.py
docs/pages/api-reference/operators.md
fennel/CHANGELOG.md
fennel/client_tests/test_dataset.py
fennel/client_tests/test_invalid.py
fennel/client_tests/test_outbrain.py
fennel/client_tests/test_search.py
fennel/client_tests/test_social_network.py
fennel/datasets/__init__.py
fennel/datasets/datasets.py
fennel/datasets/test_dataset.py
fennel/datasets/test_invalid_dataset.py
fennel/datasets/test_schema_validator.py
fennel/gen/dataset_pb2.py
fennel/gen/dataset_pb2.pyi
fennel/lib/to_proto/serializer.py
fennel/lib/to_proto/test_source_code.py
fennel/test_lib/executor.py
fennel/test_lib/mock_client.py
fennel/utils.py
pyproject.toml

This is a breaking change since we're changing the `left_join` operator to `join`.

feat: add explode and dedup operators, and inner join support

---

docs/examples/api-reference/client.py
docs/examples/datasets/operators.py
docs/examples/getting-started/quickstart.py
docs/pages/api-reference/client.md
fennel/client/client.py
fennel/client_tests/test_featureset.py
fennel/test_lib/mock_client.py
pyproject.toml

documentation: Add API documentation for extract historical

---

docs/examples/datasets/operators.py
docs/examples/getting-started/quickstart.py
fennel/CHANGELOG.md
fennel/client/client.py
fennel/client_tests/test_featureset.py
fennel/test_lib/mock_client.py
pyproject.toml

extract historical: Add timestamp to the result dataframe

---

docs/examples/api-reference/operators_ref.py
docs/pages/api-reference/operators.md
fennel/datasets/datasets.py

docs: add documentation for the new 'first' operator

---

fennel/CHANGELOG.md
pyproject.toml

This PR creates a new release for the fix in https://github.com/fennel-ai/client/pull/252

create a new release for pyclient with first operator fix

---

fennel/CHANGELOG.md
fennel/client/client.py
pyproject.toml

Sample request/response (via `fennel-ai/examples/min.py`)
*Request*
```
curl --location 'http://localhost:23103/api/v1/extract_features' \
--header 'Content-Type: application/json' \
--data '{
"input_features": [
"Request.movie_id"
],
"output_features": [
"MovieFeatures.avg_rating_1d",
"MovieFeatures.avg_rating_7d"
],
"data": {
"Request.movie_id": [
109,
100,
101,
107
]
},
"log": false,
"sampling_rate": 0.5
}'
```
*Response Body*
```
{
"MovieFeatures.avg_rating_1d": [
0.0,
1.0,
4.0,
0.0
],
"MovieFeatures.avg_rating_7d": [
0.0,
5.0,
4.0,
7.0
]
}
```

DEV-1669 DEV-1670 Convert pd dataframe to columnar based json 

---

docs/examples/api-reference/rest-api.py
docs/pages/api-reference/rest-api.md
fennel/CHANGELOG.md
fennel/client/client.py
fennel/client_tests/test_dataset.py
fennel/test_lib/integration_client.py
fennel/utils.py
pyproject.toml

There are a couple todo's still here for me to test, but we should merge this in so that changes on the server can be consumed correctly
* Test against the examples/ directory again
* look at the test_log_dataset integration test
* unit test to_columnar_json

Fixes for client after columnar change

---

fennel/client_tests/test_featureset.py

Server side e2e testing (see https://github.com/fennel-ai/server/pull/744) is more thorough, but this demonstrates e2e flow using the client

DEV-1452 add client test for extractor df handling

---

fennel/client_tests/test_featureset.py
fennel/featuresets/test_derived_extractors.py

Tests for lookup extractor with optional features / no default val

---

fennel/client_tests/test_dataset.py
fennel/client_tests/test_outbrain.py

- we should make the mock client return the same

aggregate datasets return default values when a key is not found; 

---

fennel/CHANGELOG.md
fennel/client/client.py
fennel/sources/sources.py
fennel/test_lib/mock_client.py
pyproject.toml

State breaking change for extract historical
Still need to update documentation and test

Add Creds to Extract Historical On the Client Side

---

fennel/CHANGELOG.md
fennel/client_tests/test_dataset.py
fennel/sources/sources.py
fennel/sources/test_invalid_sources.py
fennel/sources/test_sources.py
pyproject.toml

- Keeping the code in the backend to be the same to support version >=0.19.2

sources: rename pre_proc argument to preproc

---

docs/examples/api-reference/operators_ref.py
docs/examples/datasets/operators.py
docs/examples/datasets/pipelines.py
docs/examples/examples/ecommerce.py
docs/examples/getting-started/quickstart.py
docs/examples/overview/concepts.py
docs/examples/testing-and-ci-cd/unit_tests.py
fennel/client_tests/test_dataset.py
fennel/datasets/test_dataset.py
fennel/lib/aggregate/aggregate.py

added capability to specify window in str for aggregate:
1. Added tests in datasets.
2. Added tests in client_tests.
3. Added document for aggregate dataset in docs for string window.

[DEV-2320] added capability to specify window in str for aggregate

---

.wordlist.txt
docs/examples/api-reference/source.py
docs/pages/api-reference/sources.md
fennel/sources/sources.py

DEV-2542 Add Kinesis source to docs

---

.wordlist.txt
docs/examples/api-reference/source.py
docs/pages/api-reference/sources.md

Better examples, explanations, and arrangement based on BCAI feedback

DEV-2679 better kinesis source docs

---

docs/pages/api-reference/sources.md

tweak wording of permissions section for the kinesis docs

---

fennel/client_tests/test_window_operator.py
fennel/datasets/datasets.py
fennel/datasets/test_schema_validator.py
fennel/test_lib/executor.py
fennel/test_lib/mock_client.py

Added window operator mock client implementation.
Added client tests.
Please review this https://github.com/fennel-ai/client/pull/337 first.

[DEV - 2725] Added window operator mock client implementation

---

docs/examples/api-reference/source.py
docs/pages/api-reference/sources.md
fennel/CHANGELOG.md
fennel/lib/to_proto/to_proto.py
fennel/sources/__init__.py
fennel/sources/kinesis.py
fennel/sources/sources.py
fennel/sources/test_invalid_sources.py
fennel/sources/test_sources.py
pyproject.toml

DEV-2612 kinesis client changes

---

docs/examples/overview/concepts.py
docs/pages/concepts/source.md

Adding documentation for preprocessing support of sources (column default value and column aliasing) .

DEV-2667 Add documentation for Preprocessing feature 

---

docs/examples/api-reference/client.py
docs/pages/api-reference/client.md
fennel/CHANGELOG.md
fennel/client/client.py
fennel/client_tests/test_dataset.py
fennel/test_lib/mock_client.py
pyproject.toml

Added capability to do as-of in method lookup in the client

[DEV-2728] Added capability to do as-of in method lookup in the client

---

fennel/client_tests/test_complex_struct.py
fennel/datasets/datasets.py
fennel/dtypes/__init__.py
fennel/dtypes/dtypes.py
fennel/internal_lib/schema/__init__.py
fennel/internal_lib/schema/schema.py
fennel/internal_lib/to_proto/source_code.py
fennel/internal_lib/to_proto/test_to_proto.py
fennel/internal_lib/to_proto/to_proto.py
fennel/internal_lib/utils/__init__.py
fennel/lib/schema/__init__.py
fennel/testing/mock_client.py

We will now, not need to specifically add struct in includes for following cases:
1. Struct originating in featureset itself.
2. Struct originating as input from another feaureset.

[DEV 3365] Added capability to auto include struct in extractor pycode

---

fennel/CHANGELOG.md
fennel/client_tests/test_complex_window_join.py
fennel/dtypes/__init__.py
fennel/dtypes/dtypes.py
fennel/internal_lib/graph_algorithms/extractor_order.py
fennel/internal_lib/to_proto/source_code.py
fennel/lib/__init__.py
fennel/lib/functions/__init__.py
fennel/lib/functions/functions.py
fennel/testing/executor.py
fennel/testing/integration_client.py
pyproject.toml

1. Adds a helper function to get prev window for joins.

[DEV 4099] Added support for window join

---

fennel/CHANGELOG.md
fennel/client_tests/test_additional_schemas.py
fennel/internal_lib/schema/schema.py
pyproject.toml

Data schema was ignoring check for nulls when column can be nullable, added capability for that.
Also added capability to check data schema for structs.

[DEV 4409] Fix logging of optional complex dtypes in mock client

---

fennel/CHANGELOG.md
fennel/client_tests/test_featureset.py
fennel/featuresets/featureset.py
fennel/featuresets/test_derived_extractors.py
fennel/internal_lib/to_proto/to_proto.py
poetry.lock
pyproject.toml

Updated poetry lock file also.

Add support for removal of auto extractor

---

docs/examples/api-reference/operators_ref.py
fennel/datasets/datasets.py
fennel/datasets/test_dataset.py
fennel/datasets/test_invalid_dataset.py
fennel/datasets/test_schema_validator.py
pyproject.toml

Currently select throws an error if we select all columns on the server side ( since drop gets 0 columns to drop ), in such cases we do operator fusion/optimization and skip the select along with throwing a warning

operator: Select operator validation

---

1
fennel/client_tests/test_dataset.py
fennel/datasets/datasets.py
fennel/testing/executor.py
pyproject.toml

In this change we fix join, with fields value provided, on datatsets
with a same column.

Fix join with fields on datasets with a same column
