fennel-ai/client

fennel/lib/to_proto/source_code.py, fennel/lib/to_proto/test_source_code.py, pyproject.toml
We earlier used byte matching to find the lambda text, but now use a more reliable source of information i.e the offsets in the lambda ast node
=> lambda function: Fix lambda function extraction for python 3.11

docs/algolia.config.json
Tweak the algolia docsearch scraper config to change `docs.fennel.ai` => `fennel.ai/docs`
=> Fix docsearch re-indexing action

docs/pages/api-reference/sources.md, fennel/CHANGELOG.md, fennel/lib/to_proto/to_proto.py, fennel/sources/sources.py, pyproject.toml
The system will automatically fallback to using role-based access for s3 sources if access key and secret access key are not specified.
=> s3: allow creating source without credentials

docs/examples/datasets/pipelines.py, docs/pages/concepts/pipeline.md, fennel/test_utils.py
Unit test follow up to #259
`pd.to_json()` doesn't have a builtin way of the exact format we wanted: `dict[col] -> [values]`
`pd.to_dict` has this option, but `to_dict` handles `NaNs`, `Nones`, and `timestamps` differently from `to_json`.
Therefore we provide a custom function for converting dicts to columnar json. This PR provides unit tests for that function. 
I also added a couple typo fixes in the docs pages that I found as I was reading through the docs
=> DEV-1699 unit test for df -> columnar dict utility function

fennel/client_tests/test_movie_tickets.py, fennel/featuresets/featureset.py, fennel/test_lib/executor.py, fennel/test_lib/mock_client.py, fennel/utils.py, pyproject.toml
1. Make lookup semantics identical in mock client and server.
2. Make extractor input semantics identical in mock client and server.
3. Fix join asof issue in mock client.
4. Use only active pipeline in a dataset
=> experience: Client polish

docs/examples/api-reference/operators_ref.py, fennel/datasets/datasets.py, fennel/featuresets/featureset.py, fennel/lib/to_proto/test_to_proto.py, fennel/lib/to_proto/to_proto.py, fennel/test_lib/integration_client.py, pyproject.toml
This handles a corner case when an extractor does not depend on datasets, but the featureset does. The code gen for the extractor requires the featureset, which inturn requires the datasets.
Required only for compilation.
Also introduce a better error for looking up non keyed datasets
=> extract: Handle codegen for extractors that dont depend on datasets 

fennel/client_tests/test_complex_autogen_extractor.py, fennel/featuresets/featureset.py, fennel/featuresets/test_featureset.py, fennel/featuresets/test_invalid_derived_extractors.py, fennel/lib/schema/schema.py, fennel/lib/to_proto/source_code.py, fennel/lib/to_proto/to_proto.py, fennel/test_lib/mock_client.py, pyproject.toml
Code gen - when you have an extractor that does requires a provider or an alias, the code for the those featuresets should be recursively available for any extractor defined in the given featureset.
Default - After assigning defaults, the type of series is still the type for None ( when the lookup was performed ) => object, set the right type so that schema validation downstream doesn't fail
=> auto extractor: Bug fixes for code gen and default values

fennel/CHANGELOG.md, fennel/client/client.py, pyproject.toml
check_response is already called in `_get` and `_post` methods which are used by all the REST calls from the client
For a single extract features call, I see two error statements - 
```
Server returned: 500, Internal Server Error, error: FeatureSet not found: UserPageViewFeaturesFSDS
Server returned: 500, Internal Server Error, error: FeatureSet not found: UserPageViewFeaturesFSDS
```
Similarly see such errors for sync call in case sync fails completely
=> client: Report error response only once in sync and extract features call

fennel/client/client.py, fennel/datasets/test_invalid_dataset.py, fennel/test_lib/mock_client.py, fennel/test_lib/test_utils.py, pyproject.toml
1. Cast issue - See comment in fennel/test_lib/test_utils.py
2. log API in mock client takes df as param and prod client takes dataframe, making it df. This is a breaking change, but I dont think anyone uses the python log api in prod ?
=> Fix assign logging dtype checks

docs/examples/api-reference/client.py, docs/pages/api-reference/client.md
local docs rendering. Links to the S3 section on the sources page. 
With example:
=> Update docs for extract historical request

fennel/CHANGELOG.md, fennel/client_tests/test_dataset.py, fennel/datasets/datasets.py, fennel/gen/auth_pb2.py, fennel/gen/connector_pb2.py, fennel/gen/connector_pb2.pyi, fennel/gen/dataset_pb2.py, fennel/gen/expectations_pb2.py, fennel/gen/featureset_pb2.py, fennel/gen/format_pb2.py, fennel/gen/http_auth_pb2.py, fennel/gen/kinesis_pb2.py, fennel/gen/metadata_pb2.py, fennel/gen/pycode_pb2.py, fennel/gen/schema_pb2.py, fennel/gen/schema_registry_pb2.py, fennel/gen/services_pb2.py, fennel/gen/spec_pb2.py, fennel/gen/status_pb2.py, fennel/gen/window_pb2.py, fennel/lib/to_proto/to_proto.py, fennel/sources/__init__.py, fennel/sources/sources.py, fennel/sources/test_invalid_sources.py, fennel/sources/test_sources.py, fennel/test_lib/mock_client.py
This will allow the following workflows -
1. If a column doesn't exist in the upstream data source, the user could specify a constant value or refer to an existing column name.
2. If a column name in the data source is not a valid python variable (e.g. has  in the name etc), allow referencing to the column with such names.
TODO: extending types for the `pre_proc` values. Currently limiting to the ones which are frequently used.
=> sources: add pre_proc argument on sources.

fennel/CHANGELOG.md, fennel/client/client.py, fennel/client/test_client.py, fennel/client_tests/test_complex_autogen_extractor.py, fennel/client_tests/test_social_network.py, pyproject.toml
The extract historical API now specifies the `S3Table` struct so that we have a universal way of specifying an S3 config. The payload is still json based and deserialized as an ExtractHistoricalRequest on the server side, using an S3Table for s3 input and output
Note that the user interface from the client perspective does not change with this PR but the contract between client and server changes
I did test this end to end :) 
Note that this PR should go in with https://github.com/fennel-ai/server/pull/995
=> DEV-2363 change extract_historical rest call to send S3Table

docs/examples/overview/concepts.py, fennel/lib/to_proto/test_source_code.py
Using ts instead of datetime.now() to make extract_historical use as of time instead of always using current time.
=> [DEV-2653] Fixed DOB calculation logic in documentation and tests

.wordlist.txt, docs/pages/api-reference/sources.md, fennel/CHANGELOG.md, fennel/sources/sources.py, pyproject.toml
Note this PR is doing the bare minimum to make sure that `jsonl` works as a batch format for S3 for blackcrow. I haven't checked for other batch sources 
Doc Update:
=> DEV-2947 DEV-2948 Allow JSONL format for s3 sources

fennel/CHANGELOG.md, fennel/client_tests/test_data_integration.py, fennel/datasets/test_dataset_lookup.py, fennel/datasets/test_invalid_dataset.py, fennel/sources/kinesis.py, fennel/test_lib/mock_client.py, fennel/test_lib/test_cast_df_to_schema.py, fennel/test_lib/test_utils.py, pyproject.toml
1. Improved casting to timestamp from epoch time while logging into datasets.
2. Change fromtimestamp to utcfromtimestamp everywhere in the codebase.
=> [HOT FIX] Improved casting to timestamp in case of epoch

.wordlist.txt, docs/examples/api-reference/sources/s3.py, docs/pages/api-reference/connectors/deltalake.md, fennel/CHANGELOG.md, fennel/connectors/connectors.py, fennel/connectors/test_connectors.py, fennel/connectors/test_invalid_connectors.py
- Add validation around Deltalake format to support only native CDC mode
- Updated the documentation accordingly
=> Add validations around Deltalake format and update documentation

.wordlist.txt, docs/pages/api-reference/decorators/source.md, fennel/CHANGELOG.md, fennel/connectors/connectors.py, fennel/connectors/test_connectors.py, fennel/connectors/test_invalid_connectors.py
- Add validation around preproc of type A[B][C] to support only JSON format
- Updated the documentation accordingly
=> Add support for indirections in preproc ref type

docs/examples/concepts/source.py, fennel/CHANGELOG.md, fennel/client_tests/test_preproc_filter.py, fennel/datasets/datasets.py, fennel/internal_lib/to_proto/source_code.py, fennel/internal_lib/to_proto/test_source_code.py, pyproject.toml
1. Moved removal of decorators from regex to AST.
2. Added more robust way to getting function text of a lambda.
This PR fixes most of the issues, but there are still some formatting for which this fails.
=> [FIX] Added a more robust way to getting text code for where in preproc

fennel/client_tests/test_featureset.py, fennel/dtypes/dtypes.py, fennel/featuresets/featureset.py, fennel/internal_lib/schema/schema.py, fennel/testing/query_engine.py, pyproject.toml
Few more small fixes-
1. Allow only one autogenerated extractor for a given field ( else you have the same one with different defaults, but we only create a single extractor which overrides each other ), we can add this if required later.
2. Check pd.NA only if its not a list
=> extractor: Make embedding type hashable

docs/pages/api-reference/decorators/source.md, fennel/CHANGELOG.md, fennel/connectors/connectors.py, fennel/connectors/test_connectors.py, fennel/connectors/test_invalid_connectors.py, pyproject.toml
Add validation around preproc of type A[B][C] to support protobuf format for Kafka connector
Updated the documentation accordingly
=> Add support for indirections in preproc ref type for protobuf format

fennel/client_tests/test_dataset.py, fennel/internal_lib/to_proto/source_code.py, pyproject.toml
Generally any formatter corrects the comments, but customers might not run them always, so handling comments outside the pipeline function
=> source code: Handle block comments

fennel/client_tests/test_social_network.py
The test `test_social_network.py` fails in backend mode because of wrong
type assigned to a field. This change fixes the same.
=> Fix an integration test

fennel/CHANGELOG.md, fennel/client_tests/test_date_type.py, fennel/datasets/datasets.py, fennel/datasets/test_schema_validator.py, fennel/testing/execute_aggregation.py, pyproject.toml
Min and Max aggregations support finding minimum or maximum of integer, float and
decimal data types. This change adds support for date and datetime types.
=> Support date and datetime types in Min and Max aggregations

docs/pages/api-reference/decorators/source.md, fennel/CHANGELOG.md, fennel/connectors/connectors.py, fennel/connectors/test_connectors.py, fennel/connectors/test_invalid_connectors.py, pyproject.toml
Updated documentation accordingly
=> Add support for indirections in preproc ref type for Avro format

fennel/CHANGELOG.md, fennel/client/client.py, fennel/testing/mock_client.py, pyproject.toml
Add `num_dpus` parameter to `query_offline()` in `client.py` and `mock_client.py` to specify Glue DPUs for offline queries.
=> Add num dpus parameter to query offline API
